export const EVENT_TYPE :{
  readonly ALREADY_CONNECTED:string, 
  readonly GENERATE_GAME_SESSION_OFFER_ID:string,
  readonly MSG_ERROR:string,
  readonly CANCEL_OFFER_TO_PLAY:string,
  readonly JOIN_GAME:string,
  readonly JOIN_GAME_RESPONSE:string,
  readonly JUST_JOINED_GAME : string,
  readonly ALREADY_JOINED_GAME:string,
  readonly START_GAME:string,
  readonly CLOCK_TICK:string,
  readonly NEXT_TURN:string,
  readonly PLAYER_DISCONNECT_BEFORE_START:string,
  readonly PLAYER_DISCONNECT_DURING_GAME:string,
  readonly MOVE_TILE:string,
  readonly TILE_INPUT_ERROR:string,
  readonly SUBMIT_TILE: string,
  readonly PASS:string,
  readonly BOARD_CELL_OCCUPIED:string,
  readonly PAUSE_GAME:string,
  readonly RESUME_GAME:string,
  readonly SEARCH_DICT:string,
  readonly GAME_OVER:string,
  readonly REMOVE_TILE_FROM_BOARD:string,
  readonly JOIN_GAME_AFTER_DISCONNECT:string,
  readonly I_JOIN_GAME_AFTER_DISCONNECT:string,
} = {
  MSG_ERROR:"0",
  ALREADY_CONNECTED:"1",
  GENERATE_GAME_SESSION_OFFER_ID:"2",
  CANCEL_OFFER_TO_PLAY:"3",
  JOIN_GAME :"4",
  JOIN_GAME_RESPONSE:"5",
  JUST_JOINED_GAME:"6",
  ALREADY_JOINED_GAME:"7",
  START_GAME:"8",
  CLOCK_TICK:"9",
  NEXT_TURN:"10",
  PLAYER_DISCONNECT_BEFORE_START:"11",
  PLAYER_DISCONNECT_DURING_GAME:"12",
  MOVE_TILE:"13",
  TILE_INPUT_ERROR:"14",
  SUBMIT_TILE:"15",
  PASS:"16",
  BOARD_CELL_OCCUPIED:"17",
  PAUSE_GAME:"18",
  RESUME_GAME:"19",
  SEARCH_DICT:"20",
  GAME_OVER:"21",
  REMOVE_TILE_FROM_BOARD:"22",
  JOIN_GAME_AFTER_DISCONNECT:"23",
  I_JOIN_GAME_AFTER_DISCONNECT:"24",
} 